[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contribution_log_program = "2b7qVy1ikewNjFwxkUbQWMeVrNNf9NiiLVZi2hR4U7Ut"

[registry]
url = "https://api.apr.dev"

[workspace]
members = ["programs/contribution_log_program"]

[provider]
cluster = "localnet"
wallet = "C:\\Users\\SAHIL\\.config\\solana\\id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
